### PR TITLE
Improve querying audio devices

### PR DESCRIPTION
**Pull request by dyfer**
- Title: Improve querying for available audio devices
- Date proposed: June 25, 2019
- RFC PR: https://github.com/snappizz/rfcs/pull/1
- SuperCollider issue: https://github.com/supercollider/supercollider/issues/1557, https://github.com/supercollider/supercollider/issues/271

# Summary

I'd like to propose reworking of the way we can query audio devices available in the system.

# [Full RFC](https://github.com/snappizz/rfcs/blob/a2fb14cc643e5f2a649ff9cf0dd7a18e8011989c/rfcs/0000-improve-querying-for-audio-devices.md)

### CODE REVIEW

**Comment by joshpar** [comment]
This looks great... how well does it work in Linux?

**Comment by brianlheim** [comment]
> This looks great... how well does it work in Linux?

Test

**Comment by dyfer** [comment]
> This looks great... how well does it work in Linux?

In Linux this would apply if the synth would be built with PortAudio, as opposed to JACK backend (unsupported, but possible I think)

**Comment by beatboxchad** [comment]
ALSA has commands that list the audio devices, and information about them is stored in `/proc/asound/`

https://www.alsa-project.org/wiki/ALSA_Library_API

Fire up a Linux VM and code away! If I get time, this is also something I could help with.

IMO, JSON is better for data interchange, and YAML is better for configuration files a human has to author.

**Comment by snappizz** [comment]
https://github.com/supercollider/rfcs

**Pull request closed without merging**
